version: "3.9"

services:
  database:
    image: mysql
    container_name: mysql-bd
    environment:
      MYSQL_DATABASE: 'texley'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
    driver: local
