version: "3.9"

services:
  database:
    image: mysql
    container_name: texley-database
    environment:
      MYSQL_DATABASE: 'texley'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - mydb:/var/lib/mysql

volumes:
  mydb:
    driver: local
