# Generated by Django 2.2.4 on 2019-09-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='estudantes',
            field=models.ManyToManyField(related_name='estudantes', to='turmas.Estudante'),
        ),
    ]
