# Generated by Django 2.2.4 on 2019-08-17 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0002_auto_20190817_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turma',
            options={},
        ),
        migrations.AlterField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to=settings.AUTH_USER_MODEL),
        ),
    ]
