# Generated by Django 2.2.4 on 2019-09-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0002_auto_20190909_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='estudantes',
            field=models.ManyToManyField(to='turmas.Estudante'),
        ),
    ]
