# Generated by Django 2.2.4 on 2019-09-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0002_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='estudantes',
            field=models.ManyToManyField(related_name='estudantes', to='turmas.Estudante'),
        ),
    ]
