# Generated by Django 2.2.4 on 2019-09-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0003_auto_20190909_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='estudantes',
            field=models.ManyToManyField(blank=True, null=True, to='turmas.Estudante'),
        ),
    ]
